on:
  workflow_dispatch:
  schedule:
    - cron: 30 18 * * TUE
name: Weekly Q and A
jobs:
  weekly-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Weekly q and a
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.QANDA_ID }}
          webhook_token: ${{ secrets.QANDA_TOKEN }}
          username: "Weekly Q&A"
          message: Weekly Q&A starts soon, @here. If you have any questions, suggestions or other concerns we can discuss them now. Of course, you can always come to us with any other issues you might have.
